import turtle
screen = turtle.Screen()
screen.bgcolor("black")
pen = turtle.Turtle()
pen.color("pink")
pen.fillcolor("pink")
pen.pensize(3)
pen.penup()
pen.goto(0, -100)
pen.pendown()
pen.begin_fill()
pen.left(140)
pen.forward(180)
pen.circle(-90, 200)
pen.left(120)
pen.circle(-90, 200)
pen.forward(180)
pen.end_fill()
pen.penup()
pen.goto(-15, 0)
pen.pendown()
pen.color("Black")
pen.write("   LOVE ", align="center", font=("Arial", 45, "bold"))
pen.hideturtle()
screen.exitonclick()